name: hms_system_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_spinkit: ^5.2.0
  loader_overlay: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  provider: ^6.1.2
  http: ^1.2.1
  hive: ^2.2.3
  get_it: ^8.0.0
  dio: ^5.4.2+1
  f_logs: ^2.0.1
  flutter_dotenv: ^5.1.0
  geolocator: ^13.0.1
  build_runner: ^2.4.9
  path_provider: ^2.1.2
  email_validator: ^3.0.0
  video_player: ^2.9.2
  image_picker: ^1.1.2

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF" # Optional, if you want to specify a background color for Android

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.dev
