name: hms_system_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_spinkit: ^5.2.0
  loader_overlay: ^4.0.0
  provider: ^6.1.2
  http: ^1.2.1
  hive: ^2.2.3
  get_it: ^7.6.7
  dio: ^5.4.2+1
  f_logs: ^2.0.1
  flutter_dotenv: ^5.1.0
  geolocator: ^11.0.0
  build_runner: ^2.4.9
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.dev
